# -*- coding: utf-8 -*-
"""Phase2_task0b.ipynb

Automatically generated by Colaboratory.
Author: Amey Athale

Original file is located at
    https://colab.research.google.com/drive/1pdYyWBQFOAWsmqBL0-gxjY4CWNT7lxHa
"""

import pandas as pd
import numpy as np
import os
import json
import pickle
import glob
import sys

# Task 3a Part 1 user option 6:

def editdist(s, t): # for wrd files
    rows = len(s)+1
    cols = len(t)+1
    
    dist = [[0 for x in range(cols)] for x in range(rows)]

    for row in range(1, rows):
        dist[row][0] = row * 3  

    for col in range(1, cols):
        dist[0][col] = col * 3 
        
    for row in range(1, rows):
        for col in range(1, cols):
            if s[row-1] == t[col-1]:
                cost = 0
            else:
                cost = 0
                for i in range(len(s[row-1])):
                    if s[row-1][i]!=t[col-1][i]:
                        cost+=1

            dist[row][col] = min(dist[row-1][col] + 3, #deletes
                                 dist[row][col-1] + 3, #inserts
                                 dist[row-1][col-1] + cost) # substitution   
    return dist[row][col]

dir = 'data'
comp = ['X','Y','Z','W']
fnames = glob.glob("./"+dir+"/*.wrd")
fnames.sort()
sim_mat = np.zeros((len(fnames),len(fnames))) # sim matrix

for i in range(len(fnames)):
    for j in range(i,len(fnames)):
        f1 = json.load(open(fnames[i]))
        f2 = json.load(open(fnames[j]))

        temp = []
        for c in comp:
            for senid in f1[c]:
                w1 = list(np.array(f1[c][str(senid)]['words'])[:,0])
                w2 = list(np.array(f2[c][str(senid)]['words'])[:,0])
                temp.append(editdist(w1,w2))   

        f1 = os.path.splitext(os.path.basename(fnames[i]))[0]
        f2 = os.path.splitext(os.path.basename(fnames[j]))[0]

        if np.average(temp) == 0:
            sim_mat[int(f1)-1,int(f2)-1] = float('inf')
        else:
            sim_mat[int(f1)-1,int(f2)-1] = 1/np.average(temp)
            sim_mat[int(f2)-1,int(f1)-1] = 1/np.average(temp)

np.savetxt('task3a_UsrOpt6_sim_matrix.txt', sim_mat) # saves the matrix
# sim_mat = np.loadtxt('task3a_UsrOpt6_sim_matrix.txt') # use this to read the file