# -*- coding: utf-8 -*-
"""Phase2_task0b.ipynb

Automatically generated by Colaboratory.
Author: Amey Athale

Original file is located at
    https://colab.research.google.com/drive/1pdYyWBQFOAWsmqBL0-gxjY4CWNT7lxHa
"""

import pandas as pd
import numpy as np
import os
import json
import pickle
import glob
import sys

from main import phase2_EDIT_Dist as edit_distance


# Task 3a Part 1 user option 6:
dir = 'data'
fnames = glob.glob("./" + dir + "/*.wrd")
fnames.sort()
for i in range(len(fnames)):
    fnames[i] = os.path.splitext(os.path.basename(fnames[i]))[0]

df = pd.DataFrame(0.0, index=fnames, columns=fnames)

for i in range(len(fnames)):
    for j in range(i, len(fnames)):
        f1 = json.load(open('./' + dir + '/' + fnames[i] + '.wrd'))
        f2 = json.load(open('./' + dir + '/' + fnames[j] + '.wrd'))
        comp = list(f1.keys())

        temp = []
        for c in comp:
            for senid in f1[c]:
                w1 = list(np.array(f1[c][str(senid)]['words'])[:, 0])
                w2 = list(np.array(f2[c][str(senid)]['words'])[:, 0])
                temp.append(edit_distance.editdist(w1, w2))

        f1 = fnames[i]
        f2 = fnames[j]

        for k in range(len(temp)):
            temp[k] = 1 / (1 + temp[k])

        df[f1][f2] = np.average(temp)
        df[f2][f1] = np.average(temp)

df.to_csv('task3a_Edit_Dist_sim_matrix.csv')
# np.savetxt('task3a_UsrOpt6_sim_matrix.txt', sim_mat)
# sim_mat = np.loadtxt('task3a_UsrOpt6_sim_matrix.txt')
# sim_mat
